version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: chronicle
      POSTGRES_PASSWORD: chronicle
      POSTGRES_DB: chronicle_sync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      DATABASE_URL: postgresql://chronicle:chronicle@postgres:5432/chronicle_sync
      NODE_ENV: development
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  postgres_data: